env:
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash
  # Allows to run builds for the 50 last commits in a branch:
  CIRRUS_CLONE_DEPTH: 50
  SIGN_KEY: VAULT[development/team/sonarlint/kv/data/sign-key data.key_pgp]
  SIGN_PASSPHRASE: VAULT[development/team/sonarlint/kv/data/sign-key data.passphrase]
  # analysis on next
  SONAR_TOKEN: VAULT[development/kv/data/next data.token]
  SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
  SONARSOURCE_SNK: VAULT[development/team/languages/kv/data/strong_named_key data.SonarSourceSecret_snk]
  SONARSOURCE_SNK_PATH: ${CIRRUS_WORKING_DIR}/SonarSource.snk

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

container_definition: &CONTAINER_DEFINITION
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  dockerfile: .cirrus/Dockerfile
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t3.small
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}

maven_cache_definition: &MAVEN_CACHE_DEFINITION
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
    fingerprint_script:
      - find . -name pom.xml -not -path './its/*' -exec cat {} \+

compute_project_version_script_definition: &COMPUTE_PROJECT_VERSION_SCRIPT_DEFINITION |
    source cirrus-env BUILD

    # Read the version from the root pom
    sonarProjectVersion=$(maven_expression "project.version" | sed 's/-SNAPSHOT//')
    echo "Sonar project version is '${sonarProjectVersion}'"

    # Set the variable so it can be used by other tasks
    echo "SONAR_PROJECT_VERSION=${sonarProjectVersion}" >> $CIRRUS_ENV

dotnet_cache_definition: &DOTNET_CACHE_DEFINITION
  folders:
    - omnisharp-dotnet/src/Services.UnitTests
    - omnisharp-dotnet/src/Services
  fingerprint_key: ${CI_BUILD_NUMBER}

build_dotnet_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 4
    memory: 2G
  env:
    ARTIFACTORY_USER: ${ARTIFACTORY_PRIVATE_USERNAME}
    ARTIFACTORY_PASSWORD: ${ARTIFACTORY_PRIVATE_PASSWORD}
    PATH: ${PATH}:${HOME}/.dotnet/tools
    SOLUTION_PATH: omnisharp-dotnet/SonarLint.OmniSharp.DotNet.Services.sln
  dotnet_cache: *DOTNET_CACHE_DEFINITION
  compute_project_version_script: *COMPUTE_PROJECT_VERSION_SCRIPT_DEFINITION
  dotnet_restore_script: |
    # Restore the .NET project using Repox as source feed
    dotnet restore "${SOLUTION_PATH}" \
      --locked-mode \
      --configfile omnisharp-dotnet/nuget.config
  prepare_sonarqube_analysis_script: |
    # TODO Handle differences between master and PR analysis
    dotnet sonarscanner begin \
      -d:sonar.token=${SONAR_TOKEN} \
      -d:sonar.host.url=${SONAR_HOST_URL} \
      -d:sonar.projectBaseDir="${CIRRUS_WORKING_DIR}/omnisharp-dotnet/src" \
      -d:sonar.scanner.javaExePath=/opt/java/openjdk/bin/java \
      -k:"sonarlint-omnisharp-dotnet" \
      -v:${SONAR_PROJECT_VERSION} \
      -d:sonar.cs.opencover.reportsPaths="${CIRRUS_WORKING_DIR}/**/TestResults/coverage.**.xml"
  download_omnisharp_script: |
    # Get OmniSharp fork from Repox
    mvn generate-resources -B -Denable-repo=qa -DskipIts -Pdownload-omnisharp-for-building
  restore_snk_script: |
    # Restore SNK file from Vault
    echo "${SONARSOURCE_SNK}" | base64 -d > "${SONARSOURCE_SNK_PATH}"
  build_dotnet_script: |
    # Build and run .NET unit tests
    dotnet test "${SOLUTION_PATH}" \
      -c Release \
      -p:SignAssembly=true -p:AssemblyOriginatorKeyFile="${SONARSOURCE_SNK_PATH}" \
      -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover \
      --no-restore
  sonarqube_analysis_script: |
    dotnet sonarscanner end \
      -d:sonar.token=${SONAR_TOKEN}
  jarcontentfiles_artifacts:
    path: ${CIRRUS_WORKING_DIR}/omnisharp-dotnet/JarContentFiles/SonarLint.OmniSharp.DotNet.Services.dll

build_task:
  depends_on:
    - build_dotnet
  #  name: "Build and stage to repox"
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 4
    memory: 1G
  get_jarcontentfiles_script: |
    curl -O "https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build_dotnet/jarcontentfiles.zip"
    unzip jarcontentfiles.zip
  env:
    DEPLOY_PULL_REQUEST: true
  <<: *MAVEN_CACHE_DEFINITION
  build_script: |
    source cirrus-env QA
    regular_mvn_build_deploy_analyze -Dmaven.test.skip=true -Dsonar.skip=true -DskipIts
  cleanup_before_cache_script: cleanup_maven_repository

mend_scan_dotnet_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 3
    memory: 1G
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "mend-.*")
  depends_on:
    - build_dotnet
  env:
    WS_APIKEY: VAULT[development/kv/data/mend data.apikey]
  dotnet_cache: *DOTNET_CACHE_DEFINITION
  compute_project_version_script: *COMPUTE_PROJECT_VERSION_SCRIPT_DEFINITION
  whitesource_script: |
    source cirrus-env QA
    export WS_PROJECTNAME="${CIRRUS_REPO_FULL_NAME}/dotnet ${SONAR_PROJECT_VERSION}"
    export WS_PRODUCTNAME="SonarLint/OmniSharp"
    export WS_PROJECTVERSION=${SONAR_PROJECT_VERSION}
    ws_scan.sh -c ${CIRRUS_WORKING_DIR}/omnisharp-dotnet/build/whitesource/wss-unified-agent.config
  allow_failures: true
  always:
    ws_artifacts:
      path: "whitesource/**/*"
