pool:
  vmImage: 'ubuntu-latest'

# Temporarily disable the "main" analysis for changes in the dotnet subfolder.
# Will be removed as part of #2 later.
pr:
  branches:
    exclude:
    - rg/*
    - dp/*

trigger:
  branches:
    exclude:
    - branch-dotnet
    - rg/*
    - dp/*


variables:
  - group: sonarsource-build-variables

resources:
  repositories:
    - repository: commonTemplates
      type: git
      name: pipelines-yaml-templates
      ref:  refs/tags/v1.0.12


stages:
  - stage: build_dotnet
    displayName: 'Build, test and analyze .NET extension'
    variables:
      - name: buildConfiguration
        value: 'Release'  
      - name: slnPath
        value: 'omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln'

    jobs:
      - job: dotnet_build_test_test_analyze
        steps:

        - task: DownloadSecureFile@1
          displayName: 'Download snk file'
          name: snk
          inputs:
            secureFile: SonarSourceSecret.snk

        - powershell: |
            # Reads the Sonar project version to use from the Java POM file

            # Calculate the POM file path
            $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\omnisharp-plugin\pom.xml"
            Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

            # Read the version from the file
            [xml]$versionProps = Get-Content "$versionFilePath"
            $sonarProjectVersion = $versionProps.project.parent.version
            Write-Host "Sonar project version is '${sonarProjectVersion}'"

            # Set the variable to it can be used by other tasks
            Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
          displayName: 'Fetch the analysis version from the Java pom.xml'

        # Using the restore command directly seems to be the only way to explicitly limit the package feed used
        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet packages'
          inputs:
            command: 'restore'
            projects: $(slnPath)
            restoreArguments: '--locked-mode'
            feedsToUse: 'select'
            vstsFeed: '399fb241-ecc7-4802-8697-dcdd01fbb832/423b576f-2263-43a1-93bd-69f4def19102'
            includeNuGetOrg: false


        - task: SonarQubePrepare@4
          inputs:
            SonarQube: 'Next'
            scannerMode: 'MSBuild'
            projectKey: 'sonarlint-omnisharp-dotnet'
            projectName: 'sonarlint-omnisharp-dotnet'
            projectVersion: '$(SONAR_PROJECT_VERSION)'
        # NOTE: we're using coverlet -> openxml format for code coverage so we can run on non-Windows agents
            extraProperties: |
              sonar.analysis.buildNumber=$(Build.BuildId)
              sonar.analysis.pipeline=$(Build.BuildId)
              sonar.analysis.sha1=$(System.PullRequest.SourceCommitId)
              sonar.analysis.prNumber=$(System.PullRequest.PullRequestNumber)
              sonar.analysis.repository=$(Build.Repository.ID)
              sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/TestResults/coverage.**.xml"

        # Build and run can be invoked in a single "test" command.
        # This could also execute the restore, but we'd want to work out how to limit the package feed used
        - task: DotNetCoreCLI@2
          displayName: 'Build and run .NET unit tests'
          inputs:
            command: 'test'
            projects: $(slnPath)
            configuration: $(buildConfiguration)
            arguments: '-p:SignAssembly=true -p:AssemblyOriginatorKeyFile="$(snk.secureFilePath)" $(additionalMSBuildProperties) -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-restore'
            testRunTitle: '.NET unit tests'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish the jar content files as a pipeline artifact'
          inputs:
            path: omnisharp-dotnet/JarContentFiles 
            artifact: DotNetJarContentFiles
              
        - task: SonarQubeAnalyze@4

  - template: stage-with-burgr-notifications.yml@commonTemplates
    parameters:
      burgrName: 'build'
      burgrType: 'build'
      stageName: 'build'
      stageDisplayName: Build and stage to repox
      stageDependencies: build_dotnet
      jobs:
        - job: build
          displayName: Build and stage to repox
          variables:
            MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
            MAVEN_OPTS: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
            commonMavenArguments: -B -Pdeploy-sonarsource -Dmaven.test.skip=true
            fixedBranch: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
          steps:
            - checkout: self
              fetchDepth: 1
            - task: Cache@2
              inputs:
                key: 'build | maven | "$(Agent.OS)" | **/pom.xml, !its/**'
                path: $(MAVEN_CACHE_FOLDER)
              displayName: Cache Maven local repo
            - task: DownloadPipelineArtifact@2
              inputs:
                source: current
                artifact: DotNetJarContentFiles
                path: $(Pipeline.Workspace)/DotNetJarContentFiles
            - task: DownloadSecureFile@1
              displayName: 'Download Maven settings'
              name: mavenSettings
              inputs:
                secureFile: 'maven-settings.xml'
            - template: update-maven-version-steps.yml
              parameters:
                mavenSettingsFilePath: $(mavenSettings.secureFilePath)
            - task: Maven@3
              displayName: 'Run Maven deploy and sign'
              condition: ne(variables['Build.Reason'], 'PullRequest')
              env:
                ARTIFACTORY_DEPLOY_USERNAME: $(ARTIFACTORY_DEPLOY_USERNAME)
                ARTIFACTORY_DEPLOY_PASSWORD: $(ARTIFACTORY_DEPLOY_PASSWORD)
                PGP_PASSPHRASE: $(PGP_PASSPHRASE)
                GIT_SHA1: $(Build.SourceVersion)
                GITHUB_BRANCH: $(fixedBranch)
              inputs:
                goals: 'deploy'
                options: >-
                  $(commonMavenArguments)
                  --settings $(mavenSettings.secureFilePath)
                  -Prelease,sign
                  -Dsign.keyFile=$(pgpSignKey.secureFilePath)
                publishJUnitResults: false
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.11'
                mavenOptions: $(MAVEN_OPTS)
            - task: Maven@3
              displayName: 'Run Maven deploy'
              condition: eq(variables['Build.Reason'], 'PullRequest')
              env:
                ARTIFACTORY_DEPLOY_USERNAME: $(ARTIFACTORY_DEPLOY_USERNAME)
                ARTIFACTORY_DEPLOY_PASSWORD: $(ARTIFACTORY_DEPLOY_PASSWORD)
              inputs:
                goals: 'deploy'
                options: >-
                  $(commonMavenArguments)
                  --settings $(mavenSettings.secureFilePath)
                publishJUnitResults: false
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.11'
                mavenOptions: $(MAVEN_OPTS)
            - bash: git checkout .
              name: revertPomChanges
              displayName: Revert changes made to pom.xml to not break cache feature
  - template: stage-with-burgr-notifications.yml@commonTemplates
    parameters:
      burgrName: 'validate'
      burgrType: 'validate'
      stageName: 'validate'
      stageDisplayName: Run UTs and trigger SonarQube analysis
      jobs:
        - job: test_windows
          displayName: Run unit tests on Windows
          pool:
            vmImage: 'windows-latest'
          variables:
            MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
            MAVEN_OPTS: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
          steps:
            - checkout: self
              fetchDepth: 1
            - task: Cache@2
              inputs:
                key: 'validate_win | maven | "$(Agent.OS)" | **/pom.xml, !its/**'
                path: $(MAVEN_CACHE_FOLDER)
              displayName: Cache Maven local repo
            - task: DownloadSecureFile@1
              displayName: 'Download Maven settings'
              name: mavenSettings
              inputs:
                secureFile: 'maven-settings.xml'
            - task: Maven@3
              displayName: 'Run Maven verify'
              env:
                ARTIFACTORY_PRIVATE_READER_USERNAME: $(ARTIFACTORY_PRIVATE_READER_USERNAME)
                ARTIFACTORY_PRIVATE_READER_PASSWORD: $(ARTIFACTORY_PRIVATE_READER_PASSWORD)
              inputs:
                goals: 'verify'
                options: '-B --settings $(mavenSettings.secureFilePath) -Dcommercial -Denable-repo=private'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                testRunTitle: 'UTs on Windows'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.11'
                mavenOptions: $(MAVEN_OPTS)
        - job: sonarqube
          displayName: SonarQube analysis on Next
          variables:
            MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
            MAVEN_OPTS: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
          steps:
            - task: Cache@2
              inputs:
                key: 'sq | maven | "$(Agent.OS)" | **/pom.xml, !its/**'
                path: $(MAVEN_CACHE_FOLDER)
              displayName: Cache Maven local repo
            - task: DownloadSecureFile@1
              displayName: 'Download Maven settings'
              name: mavenSettings
              inputs:
                secureFile: 'maven-settings.xml'
            - template: prepare-sq-analysis-steps.yml
            - task: Maven@3
              env:
                ARTIFACTORY_PRIVATE_READER_USERNAME: $(ARTIFACTORY_PRIVATE_READER_USERNAME)
                ARTIFACTORY_PRIVATE_READER_PASSWORD: $(ARTIFACTORY_PRIVATE_READER_PASSWORD)
              inputs:
                goals: 'verify'
                options: -B --settings $(mavenSettings.secureFilePath) -Pcoverage
                publishJUnitResults: false
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.11'
                mavenOptions: $(MAVEN_OPTS)
                sonarQubeRunAnalysis: true
                sqMavenPluginVersionChoice: 'latest'
  - template: stage-with-burgr-notifications.yml@commonTemplates
    parameters:
      burgrName: 'qa'
      burgrType: 'qa'
      stageName: 'qa'
      stageDisplayName: Run ITs
      stageDependencies: build
      jobs:
        - job: its
          displayName: Run ITs
          strategy:
            matrix:
             Linux:
               imageName: 'ubuntu-latest'
             Windows:
               imageName: 'windows-latest'
             MacOS:
               imageName: 'macOS-latest'
          variables:
            MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
            MAVEN_OPTS: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
          pool:
            vmImage: $(imageName)
          steps:
            - checkout: self
              fetchDepth: 1
            - task: Cache@2
              inputs:
                key: 'its | maven | "$(Agent.OS)" | **/pom.xml'
                path: $(MAVEN_CACHE_FOLDER)
              displayName: Cache Maven local repo
            - task: DownloadSecureFile@1
              displayName: 'Download Maven settings'
              name: mavenSettings
              inputs:
                secureFile: 'maven-settings.xml'
            - template: update-maven-version-steps.yml
              parameters:
                mavenSettingsFilePath: $(mavenSettings.secureFilePath)
            - task: UseDotNet@2
              inputs:
                version: '5.0.x'
            - task: Maven@3
              displayName: 'Run Maven ITs for SQ'
              env:
                ARTIFACTORY_QA_READER_USERNAME: $(ARTIFACTORY_QA_READER_USERNAME)
                ARTIFACTORY_QA_READER_PASSWORD: $(ARTIFACTORY_QA_READER_PASSWORD)
                # For Orchestrator
                ARTIFACTORY_API_KEY: $(ARTIFACTORY_API_KEY)
                GITHUB_TOKEN: $(GITHUB_TOKEN)
                # SonarLintInstaller
                MAVEN_LOCAL_REPOSITORY: $(MAVEN_CACHE_FOLDER)
              inputs:
                goals: 'verify'
                mavenPomFile: 'its/pom.xml'
                options: '-X -B --settings $(mavenSettings.secureFilePath) -Denable-repo=qa -DskipTests=false -Pdownload-staged-artifact'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                testRunTitle: 'ITs $(imageName)'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.11'
                mavenOptions: $(MAVEN_OPTS)
            - bash: git checkout .
              name: revertPomChanges
              displayName: Revert changes made to pom.xml to not break cache feature
  - template: promote-stage.yml@commonTemplates
    parameters:
      stageDependencies:
        - validate
        - qa