# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# TODO - change triggers as part of #2
trigger:
- branch-dotnet

pr:
- branch-dotnet

pool:
  vmImage: ubuntu-latest

variables:
  - group: sonarsource-build-variables
  - name: buildConfiguration
    value: 'Release'
  - name: slnPath
    value: 'omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln'

steps:

#- script: dotnet restore omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln --locked-mode
#  displayName: 'Restore NuGet packages (locked mode)'
  
#- script: dotnet build omnisharp-dotnet/SonarLint.OmniSharp.Plugin.sln --configuration $(buildConfiguration)
#  displayName: 'dotnet build omnisharp-dotnet $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: $(slnPath)
    restoreArguments: '--locked-mode'
    feedsToUse: 'select'
    vstsFeed: '399fb241-ecc7-4802-8697-dcdd01fbb832/423b576f-2263-43a1-93bd-69f4def19102'
    includeNuGetOrg: false


- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Next'
    scannerMode: 'MSBuild'
    projectKey: 'sonarlint-omnisharp-dotnet'
    projectName: 'sonarlint-omnisharp-dotnet'
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(slnPath)
    configuration: $(buildConfiguration)
  
- task: DotNetCoreCLI@2
  displayName: 'Run .NET unit tests'
  inputs:
    command: 'test'
    projects: $(slnPath)
    configuration: $(buildConfiguration)
    nobuild: true
    testRunTitle: '.NET unit tests'
    
- task: SonarQubeAnalyze@4
