name: Cleanup PR Resources
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    name: Cleanup
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@21206070b4306949454171904b8d2b4ec349b0c5 # 2.0.1
