name: Cleanup PR Resources
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    name: Cleanup
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@62463382a24f2004ffa20adbe9985f6459e031e6 # 2.3.0
