name: Cleanup PR Resources
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: github-ubuntu-latest-s
    name: Cleanup
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@9456e3aab93a6c6d0c459b977aaa594bda102e29 # 1.4.0
